server:
  port: 5000

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
    com.cakequake.cakequakeback.shop: DEBUG
    com.cakequake.cakequakeback.cake: DEBUG
  file:
    encoding: UTF-8